import type { Change, Finding, LedgerEvent, Policy } from './domain.js';
import { appendEvent } from './ledger.js';

// Deterministic seed data (WO-002). Stable IDs and fixed timestamps so every
// startup and every reset produces byte-identical state and ledger hashes.

export interface SeedState {
  changes: Change[];
  findings: Finding[];
  policies: Policy[];
  ledger: LedgerEvent[];
}

const c = (
  id: string, title: string, source: string, summary: string,
  state: Change['state'], author: string,
): Change => ({ id, title, source, summary, state, author, routed_to: null, shipped_with_exception: false });

export function buildSeed(): SeedState {
  const changes: Change[] = [
    c('CHG-1041', 'Rotate TLS certificates on edge proxy', 'infra/edge-proxy',
      'Replaces expiring TLS certificates on the public edge proxy fleet.', 'SHIPPED', 'Priya N.'),
    c('CHG-1042', 'Add vendor export API', 'services/vendor-export',
      'New REST endpoint that exports vendor records as CSV for the procurement team. Specification and handler generated by Forge.',
      'IN_REVIEW', 'Marcus T.'),
    c('CHG-1043', 'Refactor billing webhook retries', 'services/billing',
      'Moves webhook retries to an exponential backoff queue.', 'IN_REVIEW', 'Ana L.'),
    c('CHG-1044', 'Upgrade structured logging library', 'platform/logging',
      'Bumps the logging library across 14 services.', 'APPROVED', 'Dev K.'),
    c('CHG-1045', 'Enable LLM ticket triage agent', 'apps/support-triage',
      'An agent that reads inbound support tickets and assigns priority and team.', 'IN_REVIEW', 'Sam R.'),
    c('CHG-1046', 'Customer portal dark mode', 'apps/customer-portal',
      'Adds a dark theme to the customer portal.', 'DRAFT', 'Lee W.'),
    c('CHG-1047', 'Add SSO group sync', 'services/identity',
      'Syncs IdP groups into application roles nightly.', 'IN_REVIEW', 'Jordan P.'),
    c('CHG-1048', 'Archive legacy reports job', 'jobs/reports',
      'Retires the nightly legacy report export job.', 'SHIPPED', 'Priya N.'),
  ];

  const f = (
    id: string, change: string, category: Finding['category'], severity: Finding['severity'],
    title: string, detail: string, status: Finding['status'] = 'open',
  ): Finding => ({ id, change, category, severity, status, title, detail });

  const findings: Finding[] = [
    f('F-2001', 'CHG-1042', 'secret handling', 'critical',
      'Live credential detected in generated specification',
      'live credential detected in generated specification — an access key matching a production vendor-API credential pattern (AKIA••••••••REDACTED) appears in the Authentication section of the generated OpenAPI spec.'),
    f('F-2002', 'CHG-1042', 'dependency risk', 'medium',
      'CSV serializer with known CVE',
      'The export handler depends on a CSV serializer version with a published formula-injection advisory.'),
    f('F-2003', 'CHG-1042', 'compliance gaps', 'medium',
      'Export lacks data-retention annotation',
      'The endpoint returns vendor PII without a retention or data-classification annotation required by the records policy.'),
    f('F-2004', 'CHG-1043', 'scope creep', 'low',
      'Generated code exceeds approved spec',
      'The generated diff also renames two unrelated queue metrics that were not in the approved specification.'),
    f('F-2005', 'CHG-1044', 'dependency risk', 'medium',
      'Transitive dependency pinned to deprecated major',
      'A transitive dependency of the logging library is pinned to a deprecated major version with no security backports.'),
    f('F-2006', 'CHG-1045', 'prompt injection', 'medium',
      'Ticket body flows into agent instructions',
      'Untrusted ticket text is concatenated into the agent system prompt without delimiting, allowing instruction override.'),
    f('F-2007', 'CHG-1045', 'tool exfiltration', 'low',
      'Agent tool can post to external webhook',
      'One MCP tool definition allows posting to an arbitrary URL, which could leak ticket context to an external endpoint.'),
    f('F-2008', 'CHG-1047', 'dependency risk', 'medium',
      'SAML library with outdated signature validation',
      'The SAML parsing library version has a known issue with signature-wrapping validation.'),
    f('F-2009', 'CHG-1047', 'compliance gaps', 'low',
      'Group sync lacks access-review evidence',
      'Nightly role changes are not written to the access-review evidence store.'),
    f('F-2010', 'CHG-1048', 'compliance gaps', 'low',
      'Retention schedule not updated',
      'The retired job was referenced in the records retention schedule.', 'resolved'),
  ];
  findings[9].resolution_note = 'Retention schedule updated in records register v14.';
  findings[9].resolved_by = 'Security Owner';

  const policies: Policy[] = [
    {
      id: 'POL-001',
      name: 'Secrets must not ship',
      description: 'No change may ship while an open secret-handling finding at high severity or above exists. Credentials in specs or generated code must be rotated and removed first.',
      block_severity_threshold: 'high',
      owner_role: 'Security Owner',
      applies_to: ['secret handling'],
      status: 'active',
    },
  ];

  // Seed ledger history with fixed timestamps.
  const ledger: LedgerEvent[] = [];
  const ev = (
    change: string, action: string, from: Change['state'] | null, to: Change['state'] | null,
    actor: string, timestamp: string, note: string,
  ) => appendEvent(ledger, { change, action, from_state: from, to_state: to, actor, outcome: 'success', timestamp, note });

  ev('CHG-1041', 'submit', 'DRAFT', 'IN_REVIEW', 'Developer', '2026-09-21T15:02:00.000Z', 'Submitted for review.');
  ev('CHG-1041', 'approve', 'IN_REVIEW', 'APPROVED', 'Approver', '2026-09-21T16:10:00.000Z', 'No findings. Approved.');
  ev('CHG-1041', 'ship', 'APPROVED', 'SHIPPED', 'Approver', '2026-09-21T16:40:00.000Z', 'Shipped to production.');
  ev('CHG-1048', 'submit', 'DRAFT', 'IN_REVIEW', 'Developer', '2026-09-21T17:05:00.000Z', 'Submitted for review.');
  ev('CHG-1048', 'resolve_finding', 'IN_REVIEW', 'IN_REVIEW', 'Security Owner', '2026-09-21T18:20:00.000Z', 'Resolved F-2010: Retention schedule updated in records register v14.');
  ev('CHG-1048', 'approve', 'IN_REVIEW', 'APPROVED', 'Approver', '2026-09-21T18:45:00.000Z', 'Approved.');
  ev('CHG-1048', 'ship', 'APPROVED', 'SHIPPED', 'Approver', '2026-09-21T19:00:00.000Z', 'Shipped to production.');
  ev('CHG-1044', 'submit', 'DRAFT', 'IN_REVIEW', 'Developer', '2026-09-22T14:00:00.000Z', 'Submitted for review.');
  ev('CHG-1044', 'approve', 'IN_REVIEW', 'APPROVED', 'Approver', '2026-09-22T15:30:00.000Z', 'Approved; medium dependency finding accepted as known risk.');
  ev('CHG-1043', 'submit', 'DRAFT', 'IN_REVIEW', 'Developer', '2026-09-22T16:12:00.000Z', 'Submitted for review.');
  ev('CHG-1045', 'submit', 'DRAFT', 'IN_REVIEW', 'Developer', '2026-09-22T17:48:00.000Z', 'Submitted for review.');
  ev('CHG-1047', 'submit', 'DRAFT', 'IN_REVIEW', 'Developer', '2026-09-23T09:15:00.000Z', 'Submitted for review.');
  ev('CHG-1042', 'submit', 'DRAFT', 'IN_REVIEW', 'Developer', '2026-09-23T10:02:00.000Z', 'Submitted for review. Forge security agent attached 3 findings (1 critical).');

  return { changes, findings, policies, ledger };
}
