import type { ChangeState, Severity } from './api';

// Shared presentational pieces (WO-018): severity conveyed by text + icon, not color alone.

const SEV_ICON: Record<Severity, string> = { critical: '▲', high: '▲', medium: '◆', low: '●', info: '○' };

export function SeverityBadge({ severity }: { severity: Severity }) {
  return <span className={`sev sev-${severity}`}><span aria-hidden>{SEV_ICON[severity]}</span> {severity.toUpperCase()}</span>;
}

const STATE_LABEL: Record<ChangeState, string> = {
  DRAFT: 'Draft', IN_REVIEW: 'In review', BLOCKED: 'Blocked', RESOLVED: 'Resolved', APPROVED: 'Approved', SHIPPED: 'Shipped',
};

export function StatePill({ state }: { state: ChangeState }) {
  return <span className={`state state-${state.toLowerCase()}`}>{STATE_LABEL[state]}</span>;
}

export function AiLabel({ text = 'AI-generated' }: { text?: string }) {
  return (
    <span className="ai-label" title="Generated by ShipGate's deterministic reasoning engine from live findings, policies and ledger data">
      <svg viewBox="0 0 16 16" width="12" height="12" aria-hidden><path d="M8 1l1.6 4.4L14 7l-4.4 1.6L8 13l-1.6-4.4L2 7l4.4-1.6z" fill="currentColor" /></svg>
      {text}
    </span>
  );
}

export function SimLabel() {
  return <span className="sim-label">Simulated findings feed</span>;
}

export const shortHash = (h: string) => `${h.slice(0, 8)}…${h.slice(-4)}`;

export const fmtTime = (iso: string) =>
  new Date(iso).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit' });

export function Skeleton({ lines = 3 }: { lines?: number }) {
  return <div className="skeleton">{Array.from({ length: lines }, (_, i) => <div key={i} className="sk-line" style={{ width: `${90 - i * 15}%` }} />)}</div>;
}
